#!/usr/local/bin/php
<?php

chdir(dirname(__FILE__));
date_default_timezone_set('UTC');

require_once __DIR__.'/../vendor/autoload.php';

PhpMonitor\Daemon::setFilename(__FILE__);

PhpMonitor\Daemon::getInstance()->run();

